USE [master]
GO
IF DB_ID('nombookerdb') IS NULL 
BEGIN

	CREATE DATABASE [nombookerdb]

	ALTER DATABASE [nombookerdb] MODIFY FILE
	( NAME = N'nombookerdb', SIZE = 512MB, MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )

	ALTER DATABASE [nombookerdb] MODIFY FILE
	( NAME = N'nombookerdb_log', SIZE = 256MB, MAXSIZE = UNLIMITED, FILEGROWTH = 10% )
END
GO
